---
deployment:
  tasks:
    # export variables
    - export DEPLOYPATH=/home/pokerom/public_html
    - export NPMPATH=/usr/bin/npm
    - export NODE_ENV=production
    # run commands
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp public_html/languages.php $DEPLOYPATH
    - /bin/cp public_html/info.html $DEPLOYPATH
    - $NPMPATH run pack
    - $NPMPATH restart
