---
deployment:
  tasks:
    # export variables
    - export DEPLOYPATH=/home/pokerom/public_html
    - export NPMPATH=/usr/bin/npm
    # run commands
    - /bin/cp .htaccess $DEPLOYPATH
    - $NPMPATH run pack
    - $NPMPATH restart
