---
deployment:
  tasks:
    # export variables
    - export DEPLOYPATH=/home/pokerom/public_html
    - export NPMPATH=/usr/bin/npm
    - export CPPATH=/bin/cp
    - export NODE_ENV=production
    # run commands
    - $CPPATH www/.htaccess $DEPLOYPATH
    - $CPPATH www/head_tags.inc.php $DEPLOYPATH
    - $CPPATH www/WWW.php $DEPLOYPATH
    - $CPPATH www/languages.php $DEPLOYPATH
    - $CPPATH www/info.html $DEPLOYPATH
    - $NPMPATH run pack
    - $NPMPATH restart
