---
swaggerDefinition:
  info:
    title: PokéROM API Documentation
    description: '<p><span>The API documentation for <strong>Pok&eacute;ROM</strong> (the website).</span><br/><a href="/api/docs/<%= VERSION %>" target="_self">Docs</a></p>'
    termsOfService: <%= TOS %>
    contact:
      name: API Support
      url: https://github.com/bag33188/PokeROM/issues
      email: admin@pokerom.dev
    license:
      name: ISC
      url: https://opensource.org/licenses/ISC
    version: v1
  securityDefinitions:
    bearerAuth:
      type: apiKey
      name: Authorization
      scheme: bearer
      in: header
apis:
  - './docs/definitions/*.yml'
  - './docs/paths/*.yml'
# - './docs/**/*.yml'
